"""Add notification_type to Notification

Revision ID: 27c65ba60f87
Revises: 6ffa62ac8f37
Create Date: 2025-04-15 17:55:42.718575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c65ba60f87'
down_revision = '6ffa62ac8f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('notification_type')

    # ### end Alembic commands ###
