"""Add AcademicWork model

Revision ID: 2aa72b6966ca
Revises: 2dc049b03375
Create Date: 2025-04-19 12:11:52.105232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa72b6966ca'
down_revision = '2dc049b03375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('authors_text', sa.String(length=300), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('image_file', sa.String(length=128), nullable=True),
    sa.Column('external_link', sa.String(length=255), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_academic_work_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_work'))
    )
    with op.batch_alter_table('academic_work', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_work_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_work_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_work_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_academic_work_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_work_year'))
        batch_op.drop_index(batch_op.f('ix_academic_work_title'))
        batch_op.drop_index(batch_op.f('ix_academic_work_item_type'))
        batch_op.drop_index(batch_op.f('ix_academic_work_is_published'))

    op.drop_table('academic_work')
    # ### end Alembic commands ###
