"""Add TopicApplication model

Revision ID: 2dc049b03375
Revises: db86f5723856
Create Date: 2025-04-19 10:09:34.138511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc049b03375'
down_revision = 'db86f5723856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_topic_application_post_id_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_topic_application_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topic_application')),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_user_post_application')
    )
    with op.batch_alter_table('topic_application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_application_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_application_status'))

    op.drop_table('topic_application')
    # ### end Alembic commands ###
