"""Add sender_id to Notification

Revision ID: 6ffa62ac8f37
Revises: 8fc407344da2
Create Date: 2025-04-15 17:17:33.229465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ffa62ac8f37'
down_revision = '8fc407344da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notification_sender_id_user'), 'user', ['sender_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notification_sender_id_user'), type_='foreignkey')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
