"""Add AcademicWorkLike model

Revision ID: 722e9cbe6dd8
Revises: 199377372df7
Create Date: 2025-04-19 22:12:43.202903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722e9cbe6dd8'
down_revision = '199377372df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_work_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('academic_work_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_work_id'], ['academic_work.id'], name=op.f('fk_academic_work_like_academic_work_id_academic_work'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_academic_work_like_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_work_like')),
    sa.UniqueConstraint('user_id', 'academic_work_id', name='uq_user_academic_work_like')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('academic_work_like')
    # ### end Alembic commands ###
