"""Initial schema for new setup

Revision ID: 8fc407344da2
Revises: 
Create Date: 2025-04-15 12:06:44.729322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc407344da2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('contact_email', name=op.f('uq_user_contact_email')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('student_id', name=op.f('uq_user_student_id'))
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('post_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_post_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post'))
    )
    op.create_table('student_idea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('submission_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('fk_student_idea_student_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_idea'))
    )
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=150), nullable=False),
    sa.Column('saved_filename', sa.String(length=100), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_attachment_post_id_post'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachment')),
    sa.UniqueConstraint('saved_filename', name=op.f('uq_attachment_saved_filename'))
    )
    op.create_table('idea_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=150), nullable=False),
    sa.Column('saved_filename', sa.String(length=100), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['student_idea.id'], name=op.f('fk_idea_attachment_idea_id_student_idea'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_attachment')),
    sa.UniqueConstraint('saved_filename', name=op.f('uq_idea_attachment_saved_filename'))
    )
    op.create_table('idea_recipient_lecturers',
    sa.Column('student_idea_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['user.id'], name=op.f('fk_idea_recipient_lecturers_lecturer_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_idea_id'], ['student_idea.id'], name=op.f('fk_idea_recipient_lecturers_student_idea_id_student_idea'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_idea_id', 'lecturer_id', name=op.f('pk_idea_recipient_lecturers'))
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('related_idea_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('fk_notification_recipient_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_idea_id'], ['student_idea.id'], name=op.f('fk_notification_related_idea_id_student_idea'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_timestamp'), ['timestamp'], unique=False)

    op.create_table('student_topic_interest',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('fk_student_topic_interest_post_id_post'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_student_topic_interest_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('pk_student_topic_interest'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_topic_interest')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_timestamp'))

    op.drop_table('notification')
    op.drop_table('idea_recipient_lecturers')
    op.drop_table('idea_attachment')
    op.drop_table('attachment')
    op.drop_table('student_idea')
    op.drop_table('post')
    op.drop_table('user')
    # ### end Alembic commands ###
